// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZT2DntFRJifQWayDgm2yvMFN59tsDp94',
    appId: '1:803096538535:web:4c71c744d5395d3e999a82',
    messagingSenderId: '803096538535',
    projectId: 'igcheck-app-5829',
    authDomain: 'igcheck-app-5829.firebaseapp.com',
    storageBucket: 'igcheck-app-5829.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCErLLZjKjTzSaxdcKULW6XC90lsGQT2Lw',
    appId: '1:803096538535:android:bd83789bc7ae6d32999a82',
    messagingSenderId: '803096538535',
    projectId: 'igcheck-app-5829',
    storageBucket: 'igcheck-app-5829.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBSNLZShFUT8dnC0LMZV1eqsvYXdlTz0',
    appId: '1:803096538535:ios:7b5c156b267c3b09999a82',
    messagingSenderId: '803096538535',
    projectId: 'igcheck-app-5829',
    storageBucket: 'igcheck-app-5829.firebasestorage.app',
    iosBundleId: 'com.example.igcheck.igcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZT2DntFRJifQWayDgm2yvMFN59tsDp94',
    appId: '1:803096538535:web:07c6a1d82bd6196b999a82',
    messagingSenderId: '803096538535',
    projectId: 'igcheck-app-5829',
    authDomain: 'igcheck-app-5829.firebaseapp.com',
    storageBucket: 'igcheck-app-5829.firebasestorage.app',
  );
}
